version: 0.2

phases:
  install:
    commands:
      # Update and install required packages
      - pwd
      - ls -la
      - ls -la /var/run
      - cat /etc/os-release
      - docker
      - docker ps