version: 0.2

phases:
  install:
    commands:
      - echo "Context of buildspec.yml"
      - cat terraform/codebuild/buildspec.yml
      - # Extract the tag from CODEBUILD_BUILD_ID
      - IMAGE_TAG="${CODEBUILD_BUILD_ID##*-}"
      - echo $IMAGE_TAG
      # Log in to ECR
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/h2n4d7m6
      # Build the Docker image
      - cd apps/backend/
      - docker build -t backend .
      - docker tag backend:latest public.ecr.aws/h2n4d7m6/backend:$IMAGE_TAG
      - docker push public.ecr.aws/h2n4d7m6/backend:$IMAGE_TAG
