version: 0.2

phases:
  install:
    commands:
      # Update and install required packages
      - env
      - echo $CODEBUILD_BUILD_ID
      - IMAGE_TAG="${CODEBUILD_BUILD_ID##*-}"
      - echo $IMAGE_TAG