version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing Docker"
      - cat /etc/os-release
      - docker --version
  
  build:
    commands:
      - echo "Building Docker image"
      - docker build -t backend .
      - docker tag backend:latest public.ecr.aws/h2n4d7m6/backend:latest

  post_build:
    commands:
      - echo "Pushing Docker image to AWS ECR Public registry"
      - docker push public.ecr.aws/h2n4d7m6/backend:latest

artifacts:
  files:
    - '**/*'
