version: 0.2

phases:
  install:
    commands:
      # Update and install required packages
      - apk update
      - apk add --no-cache git docker openrc python3 py3-pip
      - service docker start
      - rc-update add docker boot
      # Install AWS CLI
      - pip3 install awscli --upgrade

  pre_build:
    commands:
      - service --status-all 
      - docker --version
      - echo "Cloning GitHub repository"
      - git clone https://github.com/erdenayates/the-devops-project.git
      - cd the-devops-project/apps/backend
      - echo "Logging into AWS ECR Public registry"
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/h2n4d7m6
  
  build:
    commands:
      - echo "Building Docker image"
      - docker build -t backend .
      - docker tag backend:latest public.ecr.aws/h2n4d7m6/backend:latest

  post_build:
    commands:
      - echo "Pushing Docker image to AWS ECR Public registry"
      - docker push public.ecr.aws/h2n4d7m6/backend:latest

artifacts:
  files:
    - '**/*'
